# Generated by Django 4.2.7 on 2023-11-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=250)),
                ('model_name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
