# Generated by Django 4.2.7 on 2023-11-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carexpo_app', '0002_rename_cars_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default=1, upload_to='Uploads'),
            preserve_default=False,
        ),
    ]
